version: 2.1

jobs:
  py:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            python3 -m pip install black
     - run:
          name: Check
          command: |
            which python3
            which pip

workflows:
  main:
    jobs:
      - py
